/**
 * Kniterate `.kc` loader — decompile k-code back into a `KnitoutProgram`.
 *
 * This is the inverse of the knitout → kc export path (the vendored
 * `knitout-to-kcode.cjs`). Kniterate/Customist itself has no import, so the
 * goal here is NOT byte round-trip parity — it is **visualization fidelity**:
 * recover the knitting operations (knit / tuck / xfer / split / drop / rack /
 * carrier in-out) faithfully enough that the knitout visualizer draws the
 * same fabric. The vendor's machine choreography (carriage auto-moves, carrier
 * "kick" passes) is reconstructed from the logical ops by the visualizer /
 * backend, so we skip it here.
 *
 * How a `.kc` encodes a pass (see `src/knitout/vendor/knitout-to-kcode.cjs`):
 *   FRNT:<...>  per-slot front-bed selection  ('-' operated, '_' idle, '.' margin)
 *   REAR:<...>  per-slot rear-bed selection
 *   STIF/STIR   per-slot stitch sizes (cosmetic; not needed to render)
 *   RACK:<n>    current racking (may be fractional, e.g. 0.5)
 *   >> | <<  <type>  <carrier|0>  <speed>  <roller>     pass footer
 * The `/`, `\` and digit glyphs in FRNT/REAR are carriage / carrier *position*
 * markers (regenerated by the backend) and are ignored — only `-` matters.
 *
 * Pass `type` gives the front/back cam action:
 *   Kn-Kn / Kn-Tu / Tu-Kn / Tu-Tu   knit/tuck family (front-back)
 *   Tr-Rr / Tr-Rl                    front → rear  transfer (xfer) or split
 *   Rr-Tr / Rl-Tr                    rear → front  transfer (xfer) or split
 * carrier `0` means "no carrier": an empty knit/tuck pass is a carriage
 * auto-move (skipped); a knit/tuck pass *with* operated needles is a drop;
 * a transfer with no carrier is a plain xfer (with a carrier it is a split).
 *
 * Racking convention (verified against reference/sophie.kc in
 * `sophie/loop-stack-sim.ts`, and matching knitout's spec): front needle `f`
 * aligns with rear needle `f - rack`. We emit both beds in this front-aligned
 * coordinate so that `rack R` + `xfer f<n> b<n-R>` is valid knitout.
 */

import { parseKc, type KcPass } from './sophie/loop-stack-sim.js';
import {
  ALL_CARRIERS,
  b,
  carrierIn,
  carrierOut,
  drop,
  f,
  knit,
  rack,
  split,
  tuck,
  xfer,
  type CarrierId,
  type Direction,
  type KnitoutOp,
  type KnitoutProgram,
} from './types.js';

export interface KcToKnitoutOptions {
  /** Optional yarn names per carrier for the emitted program header. */
  yarns?: Partial<Record<CarrierId, string>>;
}

export interface KcToKnitoutStats {
  /** Total passes parsed from the `.kc`. */
  totalPasses: number;
  /** Empty carrier-`0` knit/tuck passes treated as carriage auto-moves. */
  skippedAutoMoves: number;
  /** Carrier-`0` knit/tuck passes with operated needles → emitted as drops. */
  dropPasses: number;
  /** Pass `type` strings we did not recognize, with counts (coverage signal). */
  unrecognizedTypes: Record<string, number>;
  /** Count of emitted ops by kind. */
  opCounts: Record<string, number>;
  /** Carriers that appear on any operation, sorted. */
  carriersUsed: CarrierId[];
  /** Front-aligned needle span across all emitted ops. */
  needleBounds: { min: number; max: number } | null;
  /** Racking values seen, min/max. */
  rackRange: { min: number; max: number } | null;
}

export interface KcToKnitoutResult {
  program: KnitoutProgram;
  stats: KcToKnitoutStats;
  /** Reconstructed op index -> originating `.kc` pass index; null for synthetic epilogue ops. */
  opPassIndices: readonly (number | null)[];
}

const KNIT_TUCK = /^(Kn|Tu)-(Kn|Tu)$/;
const XFER = /^(Tr-R[lr]|R[lr]-Tr)$/;

function isCarrier(c: string): c is CarrierId {
  return c === '1' || c === '2' || c === '3' || c === '4' || c === '5' || c === '6';
}

/** Decompile `.kc` text into a `KnitoutProgram` plus recovery diagnostics. */
export function kcToKnitout(kcText: string, opts: KcToKnitoutOptions = {}): KcToKnitoutResult {
  const passes = parseKc(kcText);
  const ops: KnitoutOp[] = [];
  const opPassIndices: (number | null)[] = [];
  let sourcePassIndex: number | null = null;
  const emit = (op: KnitoutOp) => {
    ops.push(op);
    opPassIndices.push(sourcePassIndex);
  };

  const unrecognizedTypes: Record<string, number> = {};
  const carriersIn = new Set<CarrierId>();
  const carriersUsed = new Set<CarrierId>();
  let skippedAutoMoves = 0;
  let dropPasses = 0;
  let currentRack: number | null = null;
  let needleMin = Infinity;
  let needleMax = -Infinity;
  let rackMin = Infinity;
  let rackMax = -Infinity;
  let seedSpeed: number | undefined;
  let seedRoller: number | undefined;

  const note = (n: number) => {
    if (n < needleMin) needleMin = n;
    if (n > needleMax) needleMax = n;
  };
  const ensureIn = (c: CarrierId) => {
    carriersUsed.add(c);
    if (!carriersIn.has(c)) {
      carriersIn.add(c);
      emit(carrierIn(c));
    }
  };
  const syncRack = (value: number) => {
    if (value < rackMin) rackMin = value;
    if (value > rackMax) rackMax = value;
    if (currentRack !== value) {
      emit(rack(value));
      currentRack = value;
    }
  };

  for (const [passIndex, pass] of passes.entries()) {
    sourcePassIndex = passIndex;
    const dir: Direction = pass.dir === '>>' ? '+' : '-';
    const r = pass.rack;
    const ri = Math.round(r); // integer needle offset for transfer pairing

    if (KNIT_TUCK.test(pass.kind)) {
      const [frontAction, backAction] = pass.kind.split('-') as ['Kn' | 'Tu', 'Kn' | 'Tu'];
      const hasNeedles = pass.f.length > 0 || pass.r.length > 0;

      if (pass.carrier === '0') {
        if (!hasNeedles) {
          skippedAutoMoves++;
          continue;
        }
        // carrier-0 selection knits = drops (loops cleared off the needles).
        dropPasses++;
        for (const col of pass.f) {
          emit(drop(f(col)));
          note(col);
        }
        for (const col of pass.r) {
          emit(drop(b(col - ri)));
          note(col - ri);
        }
        continue;
      }

      if (!isCarrier(pass.carrier)) {
        unrecognizedTypes[`carrier:${pass.carrier}`] =
          (unrecognizedTypes[`carrier:${pass.carrier}`] ?? 0) + 1;
        continue;
      }
      const carrier = pass.carrier;
      if (seedSpeed === undefined) seedSpeed = pass.speed;
      if (seedRoller === undefined) seedRoller = pass.roller;
      if (!hasNeedles) continue; // carrier present but nothing selected — skip

      syncRack(r);
      ensureIn(carrier);

      // Order operations by carriage direction so the visualizer draws the
      // yarn path correctly: '+' sweeps low→high columns, '-' high→low.
      const stitches = [
        ...pass.f.map((col) => ({ col, op: frontAction === 'Kn' ? 'knit' : 'tuck', needle: f(col), n: col })),
        ...pass.r.map((col) => ({ col, op: backAction === 'Kn' ? 'knit' : 'tuck', needle: b(col - ri), n: col - ri })),
      ];
      stitches.sort((a, c) => (dir === '+' ? a.col - c.col : c.col - a.col));
      for (const s of stitches) {
        emit(s.op === 'knit' ? knit(dir, s.needle, carrier) : tuck(dir, s.needle, carrier));
        note(s.n);
      }
      continue;
    }

    if (XFER.test(pass.kind)) {
      const frontToRear = pass.kind.startsWith('Tr-');
      syncRack(r);
      const carrier = pass.carrier !== '0' && isCarrier(pass.carrier) ? pass.carrier : null;
      if (carrier) ensureIn(carrier);

      if (frontToRear) {
        // source = front column; dest = rear needle at the same physical slot.
        for (const col of pass.f) {
          const from = f(col);
          const to = b(col - ri);
          emit(carrier ? split(dir, from, to, carrier) : xfer(from, to));
          note(col);
          note(col - ri);
        }
      } else {
        // source = rear column (back needle col - rack); dest = aligned front.
        for (const col of pass.r) {
          const from = b(col - ri);
          const to = f(col);
          emit(carrier ? split(dir, from, to, carrier) : xfer(from, to));
          note(col - ri);
          note(col);
        }
      }
      continue;
    }

    unrecognizedTypes[pass.kind] = (unrecognizedTypes[pass.kind] ?? 0) + 1;
  }

  // Bring every used carrier out at the end (ascending order).
  sourcePassIndex = null;
  for (const c of [...carriersUsed].sort()) emit(carrierOut(c));

  const opCounts: Record<string, number> = {};
  for (const op of ops) opCounts[op.kind] = (opCounts[op.kind] ?? 0) + 1;

  const program: KnitoutProgram = {
    version: 2,
    carriers: [...ALL_CARRIERS],
    machine: 'kniterate',
    yarns: opts.yarns ?? {},
    kniterate: {
      ...(seedSpeed !== undefined ? { speedNumber: seedSpeed } : {}),
      ...(seedRoller !== undefined ? { rollerAdvance: seedRoller } : {}),
    },
    ops,
  };

  const stats: KcToKnitoutStats = {
    totalPasses: passes.length,
    skippedAutoMoves,
    dropPasses,
    unrecognizedTypes,
    opCounts,
    carriersUsed: [...carriersUsed].sort(),
    needleBounds: needleMin <= needleMax ? { min: needleMin, max: needleMax } : null,
    rackRange: rackMin <= rackMax ? { min: rackMin, max: rackMax } : null,
  };

  return { program, stats, opPassIndices };
}

/** Re-export the pass type for callers that want the raw parse. */
export type { KcPass };
